In [31]:
#Random forest
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import os
os.chdir("C:\\Data Science\\social-network-ads\\")

In [32]:
social = pd.read_csv("Social_Network_Ads.csv")
social.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [38]:
X = social.iloc[:,[2,3]].values
y = social.iloc[:,4].values

In [40]:
from  sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size = 0.7, test_size =0.3, random_state = 100)

In [45]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [47]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 4.68359482e-02,  1.14942217e+00],
       [-1.38901064e+00, -1.43449573e+00],
       [-3.36056475e-01,  1.23368037e+00],
       [-1.00611821e+00, -4.79569545e-01],
       [ 4.29728371e-01,  1.03707792e+00],
       [-5.27502686e-01,  8.12389405e-01],
       [ 1.09979011e+00, -9.85118699e-01],
       [-1.44610263e-01,  1.10237802e-01],
       [-5.27502686e-01,  1.28985249e+00],
       [-1.10184132e+00,  2.78754186e-01],
       [-2.40333369e-01,  7.28131212e-01],
       [ 1.86557496e+00,  1.43028282e+00],
       [-4.88871576e-02, -3.95311353e-01],
       [-7.18948898e-01,  4.47270571e-01],
       [ 1.09979011e+00, -1.20980721e+00],
       [-2.40333369e-01, -1.37832360e+00],
       [-2.40333369e-01, -1.23789328e+00],
       [-4.88871576e-02,  1.10237802e-01],
       [-1.00611821e+00, -1.12554902e+00],
       [ 1.19551322e+00, -7.60430186e-01],
       [ 1.00406701e+00,  8.21517376e-02],
       [-1.10184132e+00,  2.50668122e-01],
       [ 8.12620794e-01, -1.37832360e+00],
       [-1.

In [52]:
#Create the model for lOgistic Regression
from sklearn.linear_model import LogisticRegression
lm = LogisticRegression(random_state = 0)

In [53]:
lm.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [54]:
#Predict 
y_pred = lm.predict(X_test)

In [55]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1], dtype=int64)

In [58]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
mt = confusion_matrix(y_test,y_pred)
mt

array([[72,  3],
       [16, 29]], dtype=int64)

In [64]:
#Finding the accuracy_score
from sklearn.metrics import accuracy_score
accuracyscore = accuracy_score(y_test,y_pred)
accuracyscore

0.8416666666666667

In [66]:
#Classofcation report of the predicted data
from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.82      0.96      0.88        75
           1       0.91      0.64      0.75        45

    accuracy                           0.84       120
   macro avg       0.86      0.80      0.82       120
weighted avg       0.85      0.84      0.83       120

